/*******************************************************************************
 * Internal utility function to read a number of bytes from a file handle and
 * copy them into video memory.  Assumes you have set up the video memory
 * auto-increment hardware address elsewhere.  Returns TRUE if successful.
 */
static bool CopyFileToVRAM(uint8_t fileId, uint16_t amountToRead)
{
  uint16_t amountRemaining;
  char *pBuffer;
  uint16_t count;

  amountRemaining = amountToRead;
  while (amountRemaining != 0) {
    if (amountRemaining > TEMPBUFFER_LEN)
      count = TEMPBUFFER_LEN;
    else
      count = amountRemaining;

    count = rn_fileHandleReadSeq(fileId, TempBuffer, 0, count);
    if (count == 0)
      break; /* End of file or error. */
    amountRemaining -= count;

    pBuffer = TempBuffer;
    for (; count != 0; count--)
      IO_VDPDATA = *pBuffer++;
  }
  return amountRemaining == 0; /* True if successful, everything read. */
}


/*******************************************************************************
 * Read a full screen picture into video ram, graphics mode 2.
 * Assumes the file is in raw pattern and colour dump as generated by Dithertron
 * https://8bitworkshop.com/dithertron/#sys=msx which gives 6K of tile pattern
 * data followed by 6K of tile colour data.  The name table is assumed to be set
 * to the identity function (position X maps to name X for each of 3 bands of
 * 256 tiles) and no sprites are used.
 *
 * Uses TempBuffer[TEMPBUFFER_LEN] defined by the main program.
 * Returns true if successful, false if it couldn't open the file or there
 * isn't enough data in the file.
 */

bool LoadScreenRaw(const char *FileName)
{
  uint8_t fileId;
  uint8_t nameLen;

  nameLen = strlen(FileName);
  fileId = rn_fileOpen(nameLen, (char *) FileName, OPEN_FILE_FLAG_READONLY,
    0xff /* Use a new file handle */);
  if (fileId == 0xff)
    return false; /* Not found? Wants uppercase, backslashes for directories! */

  playNoteDelay(0, 0, 100);

  /* Reset the name table to the identity function. */
  { /* Put in a block so i and j are temporary variables. */
    vdp_setWriteAddress(_vdpPatternNameTableAddr);
    uint8_t i = 3;
    do {
      uint8_t j = 0;
      do {
        IO_VDPDATA = j++;
      } while (j != 0);
    } while (--i != 0);
  }

  /* Load tile patterns. */

  vdp_setWriteAddress(_vdpPatternGeneratorTableAddr);
  if (!CopyFileToVRAM(fileId, 0x1800))
    return false;

  /* Load tile colours. */

  vdp_setWriteAddress(_vdpColorTableAddr);
  if (!CopyFileToVRAM(fileId, 0x1800))
    return false;

  rn_fileHandleClose(fileId);
  return true;
}

