/*******************************************************************************
 * Internal utility function to read a number of bytes from a file handle and
 * copy them into video memory.  Assumes you have set up the video memory
 * auto-increment hardware address elsewhere.  Returns TRUE if successful.
 */
static bool CopyFileToVRAM(uint8_t fileId, uint16_t amountToRead)
{
  uint16_t amountRemaining;
  char *pBuffer;
  uint16_t count;

  amountRemaining = amountToRead;
  while (amountRemaining != 0) {
    if (amountRemaining > TEMPBUFFER_LEN)
      count = TEMPBUFFER_LEN;
    else
      count = amountRemaining;

    count = rn_fileHandleReadSeq(fileId, g_TempBuffer, 0, count);
    if (count == 0)
      break; /* End of file or error. */
    amountRemaining -= count;

    pBuffer = g_TempBuffer;
    for (; count != 0; count--)
      IO_VDPDATA = *pBuffer++;
  }
  return amountRemaining == 0; /* True if successful, everything was read. */
}


/*******************************************************************************
 * Read a full screen picture into video ram.  Uses graphics mode 2, file is
 * .PC2 which is 6K of patterns (tile fonts) followed by 6K of colours (tile
 * colours).  Can be generated by web browser tool Dithertron
 * https://8bitworkshop.com/dithertron/#sys=msx  The name table is assumed to
 * be set to the identity function (position X maps to name X for each of 3
 * bands of 256 tiles) and no sprites are used.
 *
 * Uses char g_TempBuffer[TEMPBUFFER_LEN] defined by the main program.
 * Returns true if successful, false if it couldn't open the file or there
 * isn't enough data in the file.
 */

bool LoadScreenPC2(const char *FileName)
{
  uint8_t fileId;
  uint8_t nameLen;
  bool returnCode;

  returnCode = false;
  nameLen = strlen(FileName);
  fileId = rn_fileOpen(nameLen, (char *) FileName, OPEN_FILE_FLAG_READONLY,
    0xff /* Use a new file handle */);
  if (fileId == 0xff)
    return false; /* Not found? Wants uppercase, backslashes for directories! */

  /* Reset the name table to the identity function. */
  { /* Put in a block so i and j are temporary variables. */
    uint8_t i = 3;
    playNoteDelay(0, 0, 400);
    vdp_setWriteAddress(_vdpPatternNameTableAddr);
    do {
      uint8_t j = 0;
      do {
        IO_VDPDATA = j++;
      } while (j != 0);
    } while (--i != 0);
  }

  /* Load tile patterns. */

  playNoteDelay(1, 10, 400);
  vdp_setWriteAddress(_vdpPatternGeneratorTableAddr);
  if (!CopyFileToVRAM(fileId, 0x1800))
    goto ErrorExit;

  /* Load tile colours. */

  playNoteDelay(2, 20, 400);
  vdp_setWriteAddress(_vdpColorTableAddr);
  if (!CopyFileToVRAM(fileId, 0x1800))
    goto ErrorExit;

  returnCode = true;

ErrorExit:
  rn_fileHandleClose(fileId);
  return returnCode;
}

